# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abstrackr.ui'
#
# Created: Fri May 21 17:08:31 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_abstrackr_window(object):
    def setupUi(self, abstrackr_window):
        abstrackr_window.setObjectName("abstrackr_window")
        abstrackr_window.resize(1050, 618)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(abstrackr_window.sizePolicy().hasHeightForWidth())
        abstrackr_window.setSizePolicy(sizePolicy)
        abstrackr_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        abstrackr_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/abstrackr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        abstrackr_window.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(abstrackr_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.abstract_text = QtGui.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abstract_text.setFont(font)
        self.abstract_text.setFrameShape(QtGui.QFrame.StyledPanel)
        self.abstract_text.setLineWidth(4)
        self.abstract_text.setMidLineWidth(1)
        self.abstract_text.setReadOnly(True)
        self.abstract_text.setObjectName("abstract_text")
        self.verticalLayout.addWidget(self.abstract_text)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("None")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.last_study_button = QtGui.QPushButton(self.groupBox)
        self.last_study_button.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last_study_button.setFont(font)
        self.last_study_button.setAutoFillBackground(False)
        self.last_study_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/arrow_left_green_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.last_study_button.setIcon(icon1)
        self.last_study_button.setIconSize(QtCore.QSize(42, 42))
        self.last_study_button.setFlat(True)
        self.last_study_button.setObjectName("last_study_button")
        self.gridLayout_2.addWidget(self.last_study_button, 0, 10, 4, 1)
        self.accept_button = QtGui.QPushButton(self.groupBox)
        self.accept_button.setMinimumSize(QtCore.QSize(60, 60))
        self.accept_button.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.accept_button.setFont(font)
        self.accept_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/accepted_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accept_button.setIcon(icon2)
        self.accept_button.setIconSize(QtCore.QSize(64, 64))
        self.accept_button.setObjectName("accept_button")
        self.gridLayout_2.addWidget(self.accept_button, 0, 18, 4, 1)
        self.reject_button = QtGui.QPushButton(self.groupBox)
        self.reject_button.setMinimumSize(QtCore.QSize(60, 60))
        self.reject_button.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.reject_button.setFont(font)
        self.reject_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttons/cancel_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reject_button.setIcon(icon3)
        self.reject_button.setIconSize(QtCore.QSize(64, 64))
        self.reject_button.setObjectName("reject_button")
        self.gridLayout_2.addWidget(self.reject_button, 0, 19, 4, 1)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 17, 1, 1)
        self.next_study_button = QtGui.QPushButton(self.groupBox)
        self.next_study_button.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.next_study_button.setFont(font)
        self.next_study_button.setAutoFillBackground(False)
        self.next_study_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttons/arrow_right_green_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_study_button.setIcon(icon4)
        self.next_study_button.setIconSize(QtCore.QSize(42, 42))
        self.next_study_button.setFlat(True)
        self.next_study_button.setObjectName("next_study_button")
        self.gridLayout_2.addWidget(self.next_study_button, 0, 15, 4, 1)
        self.jump_button = QtGui.QPushButton(self.groupBox)
        self.jump_button.setMinimumSize(QtCore.QSize(0, 30))
        self.jump_button.setMaximumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.jump_button.setFont(font)
        self.jump_button.setObjectName("jump_button")
        self.gridLayout_2.addWidget(self.jump_button, 1, 13, 1, 1)
        self.labellabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labellabel.setFont(font)
        self.labellabel.setObjectName("labellabel")
        self.gridLayout_2.addWidget(self.labellabel, 2, 6, 1, 1)
        self.lbl_lbl = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_lbl.setFont(font)
        self.lbl_lbl.setObjectName("lbl_lbl")
        self.gridLayout_2.addWidget(self.lbl_lbl, 2, 8, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 6, 1, 1)
        self.refman_id_lbl = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.refman_id_lbl.setFont(font)
        self.refman_id_lbl.setText("")
        self.refman_id_lbl.setObjectName("refman_id_lbl")
        self.gridLayout_2.addWidget(self.refman_id_lbl, 1, 8, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 3, 6, 1, 1)
        self.jump_txt = QtGui.QLineEdit(self.groupBox)
        self.jump_txt.setMaximumSize(QtCore.QSize(40, 16777215))
        self.jump_txt.setObjectName("jump_txt")
        self.gridLayout_2.addWidget(self.jump_txt, 1, 12, 2, 1)
        self.pos_term_btn1 = QtGui.QPushButton(self.groupBox)
        self.pos_term_btn1.setEnabled(False)
        self.pos_term_btn1.setMinimumSize(QtCore.QSize(60, 60))
        self.pos_term_btn1.setMaximumSize(QtCore.QSize(60, 60))
        self.pos_term_btn1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttons/thumbs_up_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pos_term_btn1.setIcon(icon5)
        self.pos_term_btn1.setIconSize(QtCore.QSize(60, 60))
        self.pos_term_btn1.setCheckable(False)
        self.pos_term_btn1.setFlat(False)
        self.pos_term_btn1.setObjectName("pos_term_btn1")
        self.gridLayout_2.addWidget(self.pos_term_btn1, 0, 2, 1, 1)
        self.neg_term_btn1 = QtGui.QPushButton(self.groupBox)
        self.neg_term_btn1.setEnabled(False)
        self.neg_term_btn1.setMinimumSize(QtCore.QSize(60, 60))
        self.neg_term_btn1.setMaximumSize(QtCore.QSize(60, 60))
        self.neg_term_btn1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/buttons/thumbs_down_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.neg_term_btn1.setIcon(icon6)
        self.neg_term_btn1.setIconSize(QtCore.QSize(60, 60))
        self.neg_term_btn1.setObjectName("neg_term_btn1")
        self.gridLayout_2.addWidget(self.neg_term_btn1, 0, 3, 1, 1)
        self.neg_term_btn2 = QtGui.QPushButton(self.groupBox)
        self.neg_term_btn2.setEnabled(False)
        self.neg_term_btn2.setMinimumSize(QtCore.QSize(60, 60))
        self.neg_term_btn2.setMaximumSize(QtCore.QSize(60, 60))
        self.neg_term_btn2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/buttons/two_thumbs_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.neg_term_btn2.setIcon(icon7)
        self.neg_term_btn2.setIconSize(QtCore.QSize(60, 60))
        self.neg_term_btn2.setObjectName("neg_term_btn2")
        self.gridLayout_2.addWidget(self.neg_term_btn2, 0, 4, 1, 1)
        self.pos_term_btn2 = QtGui.QPushButton(self.groupBox)
        self.pos_term_btn2.setEnabled(False)
        self.pos_term_btn2.setMinimumSize(QtCore.QSize(60, 60))
        self.pos_term_btn2.setMaximumSize(QtCore.QSize(60, 60))
        self.pos_term_btn2.setBaseSize(QtCore.QSize(0, 0))
        self.pos_term_btn2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/buttons/two_thumbs_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pos_term_btn2.setIcon(icon8)
        self.pos_term_btn2.setIconSize(QtCore.QSize(60, 60))
        self.pos_term_btn2.setObjectName("pos_term_btn2")
        self.gridLayout_2.addWidget(self.pos_term_btn2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        abstrackr_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(abstrackr_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 20))
        self.menubar.setObjectName("menubar")
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        abstrackr_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(abstrackr_window)
        self.statusbar.setObjectName("statusbar")
        abstrackr_window.setStatusBar(self.statusbar)
        self.action_edit_terms = QtGui.QAction(abstrackr_window)
        self.action_edit_terms.setObjectName("action_edit_terms")
        self.menuData.addAction(self.action_edit_terms)
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(abstrackr_window)
        QtCore.QMetaObject.connectSlotsByName(abstrackr_window)

    def retranslateUi(self, abstrackr_window):
        abstrackr_window.setWindowTitle(QtGui.QApplication.translate("abstrackr_window", "(abstrackr beta)", None, QtGui.QApplication.UnicodeUTF8))
        self.jump_button.setText(QtGui.QApplication.translate("abstrackr_window", "jump", None, QtGui.QApplication.UnicodeUTF8))
        self.labellabel.setText(QtGui.QApplication.translate("abstrackr_window", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_lbl.setText(QtGui.QApplication.translate("abstrackr_window", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("abstrackr_window", "RefMan ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuData.setTitle(QtGui.QApplication.translate("abstrackr_window", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit_terms.setText(QtGui.QApplication.translate("abstrackr_window", "annotations ...", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
